NpaManagerMVC/Controllers/IogvRefsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NpaManagerMVC.Models {
   public class IogvRefsController:Controller {
      private NpaDbContext db = new NpaDbContext();

      // GET: IogvRefs
      public ActionResult Index() {
         var list = db.IogvRefs.ToList();
         return View(list);
      }

      // GET: IogvRefs/Details/5
      public ActionResult Details(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         IogvRef iogvRef = db.IogvRefs.Find(id);
         if(iogvRef == null) {
            return HttpNotFound();
         }
         return View(iogvRef);
      }

      // GET: IogvRefs/Create
      public ActionResult Create() {
         return View();
      }

      // POST: IogvRefs/Create
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "Iogv")] IogvRef iogvRef) {
         if(ModelState.IsValid) {
            db.IogvRefs.Add(iogvRef);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(iogvRef);
      }

      // GET: IogvRefs/Edit/5
      public ActionResult Edit(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         IogvRef iogvRef = db.IogvRefs.Find(id);
         if(iogvRef == null) {
            return HttpNotFound();
         }
         return View(iogvRef);
      }

      // POST: IogvRefs/Edit/5
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "Iogv")] IogvRef iogvRef) {
         if(ModelState.IsValid) {
            db.Entry(iogvRef).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(iogvRef);
      }

      // GET: IogvRefs/Delete/5
      public ActionResult Delete(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         IogvRef iogvRef = db.IogvRefs.Find(id);
         if(iogvRef == null) {
            return HttpNotFound();
         }
         return View(iogvRef);
      }

      // POST: IogvRefs/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(string id) {
         IogvRef iogvRef = db.IogvRefs.Find(id);
         db.IogvRefs.Remove(iogvRef);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing) {
         if(disposing) {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

NpaManagerMVC/Controllers/PeriodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NpaManagerMVC.Models;

namespace NpaManagerMVC.Controllers {
   public class PeriodsController:Controller {
      private NpaDbContext db = new NpaDbContext();

      // GET: Periods
      public ActionResult Index() {
         var periods = db.Periods.OrderBy(i => i.DateFirst);
         return View(periods.ToList());
      }

      // GET: Periods/Details/5
      public ActionResult Details(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Period period = db.Periods.Find(id);
         if(period == null) {
            return HttpNotFound();
         }
         return View(period);
      }

      // GET: Periods/Create
      public ActionResult Create() {
         return View();
      }

      // POST: Periods/Create
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "PeriodId,Year,Quaretr,DateFirst,DateEnd,Editable,Browsable")] Period period) {
         if(ModelState.IsValid) {
            db.Periods.Add(period);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(period);
      }

      // GET: Periods/Edit/5
      public ActionResult Edit(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Period period = db.Periods.Find(id);
         if(period == null) {
            return HttpNotFound();
         }
         return View(period);
      }

      // POST: Periods/Edit/5
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "PeriodId,Year,Quaretr,DateFirst,DateEnd,Editable,Browsable")] Period period) {
         if(ModelState.IsValid) {
            db.Entry(period).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(period);
      }

      // GET: Periods/Delete/5
      public ActionResult Delete(string id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Period period = db.Periods.Find(id);
         if(period == null) {
            return HttpNotFound();
         }
         return View(period);
      }

      // POST: Periods/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(string id) {
         Period period = db.Periods.Find(id);
         db.Periods.Remove(period);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing) {
         if(disposing) {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

NpaManagerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>@ViewBag.Title - График НПА</title>
   @Styles.Render("~/Content/css")
   @Scripts.Render("~/bundles/modernizr")

</head>
<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("График НПА", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
         </div>
         <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <li>@Html.ActionLink("Home", "Index", "Home")</li>
               <li>@Html.ActionLink("About", "About", "Home")</li>
               <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
               <li>@Html.ActionLink("Периоды", "Index", "Periods")</li>
               <li>@Html.ActionLink("По органам власти", "Index", "IogvRefs")</li>
            </ul>
            @Html.Partial("_LoginPartial")
         </div>
      </div>
   </div>
   <div class="container body-content">
      @RenderBody()
      <hr />
      <footer>
         <p>&copy; @DateTime.Now.Year - КИТС ЕАО</p>
      </footer>
   </div>

   @Scripts.Render("~/bundles/jquery")
   @Scripts.Render("~/bundles/bootstrap")
   @RenderSection("scripts", required: false)
</body>
</html>